import React from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientProvider from './clientProvider';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export async function generateMetadata() {
    return {
        title: "HHH Community",
        description: "Generated by create next app",
        viewport: "width=device-width, initial-scale=1", // Outros valores opcionais
    };
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
