import React from "react";
import ClientProvider from "./clientProvider";

export const metadata = {
    title: "HHH Community",
    description: "Generated by create next app",
};

export const viewport = {
    width: "device-width",
    initialScale: 1,
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
      <html lang="en">
        <head>
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&family=Bitter:ital,wght@0,100..900;1,100..900&family=JetBrains+Mono:wght@100..700&display=swap"
          />
        </head>
        <body className="min-h-screen bg-background bg-[url('/bg-site.jpg')] bg-repeat dark:bg-none transition-colors duration-200">
          <ClientProvider>{children}</ClientProvider>
        </body>
      </html>
    );
}
